### ISSUE TITLE
test_hbone_request and test_tcp_request flakes with nextest

### ISSUE THREAD

**Issue by stevenctl** [istio/ztunnel#208]
I was experimenting with [nextest](https://nexte.st/) which is supposedly faster than `cargo test` and I get a failure for `test_hbone_request`  maybe 80% of the time. 

I never see a failure when I add `--test-threads=1`. 

Not sure if this is purely an issue with the test runner. Possibly indicates a deeper issue but I have not looked closely yet. 

```
--- STDERR:              ztunnel::proxy test_hbone_request ---
thread 'test_hbone_request' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "early eof" }', tests/proxy.rs:84:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
--- STDERR:              ztunnel::proxy test_tcp_request ---
thread 'test_tcp_request' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "early eof" }', tests/proxy.rs:84:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by stevenctl** [comment]
other note: in the cases where `nextest` passes, there is no speedup. I think it's due to `test_cache_refresh`. If we had a ton of tests it'd likely be a speedup.

**Comment by PiotrSikora** [comment]
Are you testing on the current `master`? The race condition between config parsing and listeners was fixed over the weekend (see: #195 and #196).

**Comment by howardjohn** [comment]
From master:

```
running 1 test
2022-11-28T18:32:12.997933Z  INFO ztunnel::proxy::inbound: running without transparent mode
2022-11-28T18:32:12.998309Z  INFO ztunnel::proxy::outbound: running without transparent mode
2022-11-28T18:32:12.998696Z  INFO ztunnel::admin: Serving admin server at [::]:43183
2022-11-28T18:32:12.998754Z  INFO ztunnel::workload: running local client
2022-11-28T18:32:12.999021Z  INFO ztunnel::proxy::inbound_passthrough: running without transparent mode
2022-11-28T18:32:12.999047Z  INFO ztunnel::proxy::inbound_passthrough: inbound plaintext listener established [::]:33255
2022-11-28T18:32:12.999085Z  INFO ztunnel::proxy::inbound: HBONE listener established [::]:38083
2022-11-28T18:32:12.999117Z  INFO ztunnel::proxy::outbound: outbound listener established [::]:44867
2022-11-28T18:32:12.999161Z  INFO ztunnel::proxy::socks5: socks5 listener established [::]:43727
2022-11-28T18:32:12.999310Z  INFO ztunnel::proxy::socks5: accepted outbound connection from [::ffff:127.0.0.1]:46012
2022-11-28T18:32:12.999531Z  INFO ztunnel::proxy::socks5: accepted connection from 127.0.0.1 to 127.0.0.2:35775
2022-11-28T18:32:12.999630Z  WARN ztunnel::proxy::socks5: outbound proxy failed: unknown source: 127.0.0.1
test test_tcp_request ... FAILED

failures:

---- test_tcp_request stdout ----
thread 'test_tcp_request' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: UnexpectedEof, error: "early eof" }', tests/proxy.rs:93:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_tcp_request

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.02s
```

**Comment by PiotrSikora** [comment]
I'm kind of confused how we could reach `proxy.run()` before loading of workloads completes.

We're blocking progress on `WorkloadManager` here: https://github.com/istio/ztunnel/blob/e0bb9a388ab97d5bfff422530617ab88432e81d6/src/app.rs#L41

which is blocked on reading workloads from `LocalClient` here:
https://github.com/istio/ztunnel/blob/e0bb9a388ab97d5bfff422530617ab88432e81d6/src/workload.rs#L259

From Tokio docs, it looks that [tokio::fs::read_to_string](https://docs.rs/tokio/latest/tokio/fs/fn.read_to_string.html) is spawned on another thread, but the progress in the `App` should be blocked by the chain of `await`s, unless I'm missing something about `async/await`: https://github.com/istio/ztunnel/blob/e0bb9a388ab97d5bfff422530617ab88432e81d6/src/workload.rs#L291-L302

**Comment by PiotrSikora** [comment]
I cannot replicate this issue in my local environment, but could you add `info!("read {} bytes", data.len());` in `LocalClient::run()` after `read_to_string` to see if the file is read correctly?

**Comment by howardjohn** [comment]
Its weird... I could reproduce earlier but not anymore. Starting to think maybe I was somehow not on master before...?

**Comment by howardjohn** [comment]
Steven and I both couldn't replicate anymore, I think this was fixed
