### ISSUE TITLE
Possible segfault

### ISSUE THREAD

**Issue by howardjohn** [istio/ztunnel#489]
From `cargo bench connections/hbone -- --profile-time 10`
```
(gdb) bt
#0  0x00007ffff7f9e8ee in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007ffff7fa064b in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x0000555555a44eeb in perf_signal_handler ()
#3  <signal handler called>
#4  0x0000555555e03cf0 in ecp_nistz256_ord_mul_mont ()
#5  0x0000000000000212 in ?? ()
#6  0x6f05ab71aa947b60 in ?? ()
#7  0xe8ef83dd782ece3a in ?? ()
#8  0xdda4b5e439a881af in ?? ()
#9  0x0000555555e04a9e in ecp_nistz256_mul_mont ()
#10 0x00007fff7d5e1a70 in ?? ()
#11 0x0000555555dfe020 in ONE ()
#12 0x00007fff7d5e1a10 in ?? ()
#13 0x00007fff7d5e1ab0 in ?? ()
#14 0x00007fff7d5e1ba0 in ?? ()
#15 0x000000000000000a in ?? ()
#16 0x0000555555dd2ec9 in ecp_nistz256_inv0_mod_ord (group=<optimized out>, out=0x7fff7d5e1970, in=<optimized out>) at /boringssl/build/../crypto/fipsmodule/ec/p256-x86_64.c:551
#17 0x0000555555d8fe9c in ec_scalar_inv0_montgomery (group=0x555556144a58, r=0x7fff7d5e1ba0, a=0x7fff7d5e1f20) at /boringssl/build/../crypto/fipsmodule/ec/scalar.c:169
#18 ecdsa_sign_impl (group=<optimized out>, group@entry=0x555556144a58, out_retry=out_retry@entry=0x7fff7d5e1dfc, priv_key=priv_key@entry=0x7fffb8001690, k=<optimized out>,
    k@entry=0x7fff7d5e1f20, digest=<optimized out>,
    digest@entry=0x7fff7d5e2090 "\342\377\f\213(\343\002Y\231\276(\a|\b\357i \374\034 t\303-\201\346틷\224\377\242H\300!^}\377\177", digest_len=digest_len@entry=32)
    at /boringssl/build/../crypto/fipsmodule/ecdsa/ecdsa.c:247
#19 0x0000555555d904f9 in ECDSA_do_sign (digest=0x7fff7d5e2090 "\342\377\f\213(\343\002Y\231\276(\a|\b\357i \374\034 t\303-\201\346틷\224\377\242H\300!^}\377\177", digest_len=32,
    eckey=<optimized out>, eckey@entry=0x7fffb8001538) at /boringssl/build/../crypto/fipsmodule/ecdsa/ecdsa.c:334
#20 0x0000555555e5fd26 in ECDSA_sign (type=<optimized out>, digest=<optimized out>, digest_len=<optimized out>, sig=0x7fffb4026b90 "", sig_len=0x7fff7d5e2024, eckey=0x7fffb8001538)
    at ../crypto/ecdsa_extra/ecdsa_asn1.c:77
#21 0x0000555555e6669c in pkey_ec_sign (ctx=<optimized out>, sig=0x7fffb4026b90 "", siglen=0x7fff7d5e21c0,
    tbs=0x7fff7d5e2090 "\342\377\f\213(\343\002Y\231\276(\a|\b\357i \374\034 t\303-\201\346틷\224\377\242H\300!^}\377\177", tbslen=32) at ../crypto/evp/p_ec.c:131
#22 0x0000555555e63529 in EVP_DigestSignFinal (ctx=0x7fff7d5e2118, out_sig=0x7fffb4026b90 "", out_sig_len=0x7fff7d5e21c0) at ../crypto/evp/digestsign.c:165
#23 0x0000555555edb4a7 in bssl::ssl_private_key_sign (hs=<optimized out>, hs@entry=0x7fffb4047fc8, out=0x7fffb4026b90 "", out_len=out_len@entry=0x7fff7d5e21c0,
    max_out=max_out@entry=72, sigalg=1027, in=...) at ../ssl/ssl_privkey.cc:229
#24 0x0000555555eeedf0 in bssl::tls13_add_certificate_verify (hs=hs@entry=0x7fffb4047fc8) at ../ssl/tls13_both.cc:604
#25 0x0000555555eefa4a in bssl::do_send_client_certificate_verify (hs=0x7fffb4047fc8) at ../ssl/tls13_client.cc:801
#26 bssl::tls13_client_handshake (hs=hs@entry=0x7fffb4047fc8) at ../ssl/tls13_client.cc:904
#27 0x0000555555ec33e3 in bssl::do_tls13 (hs=0x7fffb4047fc8) at ../ssl/handshake_client.cc:791
#28 bssl::ssl_client_handshake (hs=<optimized out>) at ../ssl/handshake_client.cc:1757
#29 0x0000555555ec21e3 in bssl::ssl_run_handshake (hs=0x7fffb4047fc8, out_early_return=out_early_return@entry=0x7fff7d5e27bf) at ../ssl/handshake.cc:726
#30 0x0000555555ed6c13 in SSL_do_handshake (ssl=0x7fffb4046ed8) at ../ssl/ssl_lib.cc:888
#31 0x00005555557a4654 in <tokio_boring::HandshakeFuture<S> as core::future::future::Future>::poll ()
#32 0x0000555555782a48 in ztunnel::proxy::outbound::OutboundConnection::proxy_to::{{closure}} ()
#33 0x0000555555774864 in ztunnel::proxy::socks5::handle::{{closure}}::{{closure}} ()
#34 0x000055555571be72 in tokio::runtime::task::raw::poll ()
```

I am not 100% sure its a real issue vs some corrupted state I had in my local env, I was doing some wonky things.

**Comment by howardjohn** [comment]
Moved off boring, so closing this for now
